DROP TABLE Customer CASCADE;
DROP TABLE Farm CASCADE;
DROP TABLE Field CASCADE;
/*
DROP TABLE Rents CASCADE;
*/
DROP TABLE Contracts CASCADE;
DROP TABLE Product CASCADE;
DROP TABLE For_prod CASCADE;
DROP TABLE Shed CASCADE;
DROP TABLE Bin CASCADE;
DROP TABLE Bale CASCADE;
DROP TABLE Grain CASCADE;
DROP TABLE Wheat CASCADE;
DROP TABLE Barley CASCADE;
DROP TABLE Canola CASCADE;
