DELETE TABLE Customer CASCADE;
DELETE TABLE Farm CASCADE;
DELETE TABLE Field CASCADE;
/*
DELETE TABLE Rents CASCADE;
*/
DELETE TABLE Contracts CASCADE;
DELETE TABLE Product CASCADE;
DELETE TABLE For_prod CASCADE;
DELETE TABLE Shed CASCADE;
DELETE TABLE Bin CASCADE;
DELETE TABLE Bale CASCADE;
DELETE TABLE Grain CASCADE;
DELETE TABLE Wheat CASCADE;
DELETE TABLE Barley CASCADE;
DELETE TABLE Canola CASCADE;
